nelmio_cors:
    defaults:
        allow_origin: ['https://nuvia-frontend-8ys1.vercel.app']
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/': ~