[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.intl"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php bin/console cache:warmup --env=prod"
]
